Product_selection:
  Data_sources:
    - SEXTANT
    - ODATIS
  Sensor_names:
    - merged
    - modis
  Satellite_variables:
    - SPM
  Atmospheric_corrections:
    - Standard
    - polymer
  Regions:
    - GULF_OF_LION


Period_selection:
  start_day: '2020/01/01'
  end_day: '2020/01/31'


Temporal_resolution:
  Temporal_resolution_of_global_maps_to_download:
    - DAILY
  Temporal_resolution_of_regional_maps:
    - WEEKLY
  Temporal_resolution_of_plume_detection:
    - WEEKLY
  



