Paths:
  Package_root: '/media/shared_storage/Documents/CODING/PROJECTS/myRIOMAR_dev'
  Where_to_save_satellite_global_map: '/media/shared_storage/Documents/CODING/RESULTS/myRIOMAR'
  Where_to_save_results: '/media/shared_storage/Documents/CODING/RESULTS/myRIOMAR'
